version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    environment:
       DOCKER_IMAGE_NAME: registry.uw.systems/utilitywarehouse/$CIRCLE_PROJECT_REPONAME
    working_directory: /tmp
    steps:
      - setup_remote_docker
      - run: 'apk add --no-cache docker'
      - run: |
        docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .
        docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_IMAGE_NAME:latest
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker push $DOCKER_IMAGE_NAME
