version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    environment:
       DOCKER_IMAGE_NAME: registry.uw.systems/utilitywarehouse/$CIRCLE_PROJECT_REPONAME
    working_directory: /go/src/github.com/utilitywarehouse/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          apk add --no-cache docker
      - run: |
          docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .
          docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_IMAGE_NAME:latest
          docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.uw.systems
          docker push $DOCKER_IMAGE_NAME
