version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    environment:
       REGISTRY: registry.uw.systems
       PROJECT_NAME: utilitywarehouse/$CIRCLE_PROJECT_REPONAME
       DOCKER_IMAGE_NAME: $REGISTRY/$PROJECT_NAME
    working_directory: /go/src/github.com/$PROJECT_NAME
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          apk add --no-cache docker
      - run: |
          docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .
          docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_IMAGE_NAME:latest
          docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY
          docker push $DOCKER_IMAGE_NAME
