version: '2'

services:
  redis:
    image: redis:alpine
    container_name: gskp-redis
    ports:
     - '6379:6379'
  redis-auth:
    image: redis:alpine
    container_name: gskp-redis-auth
    command: --requirepass password
    ports:
     - '6380:6379'
