apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: github-sshkey-provider
  name: github-sshkey-provider-agent
spec:
  template:
    metadata:
      labels:
        app: github-sshkey-provider
        appComponent: agent
      name: github-sshkey-provider-agent
    spec:
      containers:
      - name: agent
        image: utilitywarehouse/github-sshkey-provider
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
        args:
          - agent
        env:
        - name: GSKP_REDISHOST
          value: github-sshkey-provider:6379
        - name: GSKP_REDISPASSWORD
          valueFrom:
            secretKeyRef:
              name: github-sshkey-provider-secrets
              key: redis-password
        - name: GSKP_AGENTBOOTSTRAPURL
          value: http://github-sshkey-provider/authorized_keys
        - name: GSKP_AUTHORIZEDKEYSPATH
          value: /authorized_keys
        volumeMounts:
        - name: github-sshkey-provider-collector-authorizedkeys
          mountPath: /authorized_keys
          readOnly: false
      volumes:
      - name: github-sshkey-provider-collector-authorizedkeys
        hostPath:
          path: /home/core/.ssh/authorized_keys
      imagePullSecrets:
        - name: dockerhub-key
